### ISSUE TITLE
Compilation error for `Kopy` annotated classes due to generated atomicfu properties

### ISSUE THREAD

**Issue by sureshg** [JavierSegoviaCordoba/kopy#37]
Here is the sample data classes

```kotlin
import com.javiersc.kotlin.kopy.Kopy
import dev.zacsweers.redacted.annotations.Redacted

@Kopy data class Person(val name: Name, val address: Address, val privateInfo: PrivateInfo)

@Kopy data class Name(val first: String, val last: String)

@Kopy data class Address(val street: String, val city: String, val state: String, val zip: String)

data class PrivateInfo(@Redacted val ssn: String, @Redacted val dob: String)
```

* Error

```kotlin
e: java.lang.IllegalStateException: Failed to find initialization of the property [PROPERTY GENERATED[com.javiersc.kotlin.kopy.compiler.fir.Key] name:_atomic visibility:internal modality:FINAL [val]] in the init block of the class [CLASS CLASS name:Person modality:FINAL visibility:public [data] superTypes:[kotlin.Any]].
Please avoid complex data flow in property initialization, e.g. instead of this:

val a: AtomicInt
init {
  if (foo()) {
    a = atomic(0)
  } else {
    a = atomic(1)
  }
}
use simple direct assignment expression to initialize the property:

val a: AtomicInt
init {
  val initValue = if (foo()) 0 else 1
  a = atomic(initValue)
}


Please make sure that you follow these constraints for using atomic properties:
   * To ensure that atomic properties are not accessed out of the current Kotlin module, it is necessary to declare atomic properties as private or internal.
     Alternatively, you can make the containing class private or internal.
     If you need to expose the atomic property value to the public, consider using a delegated property declared within the same scope:

       private val _a = atomic<T>(initial)
       public var a: T by _a

   * Directly invoke operations on atomic properties, like this:

       val top = atomic<Node?>(null)
       top.compareAndSet(null, Node(1)) // OK

   * Refrain from invoking atomic operations on local variables:

       val top = atomic<Node?>(null)
       val tmp = top
       tmp.compareAndSet(null, Node(1)) // DON'T DO THIS

   * Avoid leaking references to atomic values in other ways, such as returning them or passing them as parameters.
   * Be cautious with the complexity of data flow within parameters of atomic operations.
     For instance, instead of using intricate expression directly as an argument, e.g.:

       top.compareAndSet(cur, <complex_expression>)

     create a separate variable to hold the complex expression's value and then perform the operation:

       val newValue = <complex_expression>
       top.compareAndSet(cur, newValue)



        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.getInitBlockForField(AbstractAtomicfuTransformer.kt:429)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.buildVolatileBackingField(AbstractAtomicfuTransformer.kt:305)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.jvm.AtomicfuJvmIrTransformer$JvmAtomicPropertiesTransformer.addVolatilePropertyWithAtomicUpdater(AtomicfuJvmIrTransformer.kt:101)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.jvm.AtomicfuJvmIrTransformer$JvmAtomicPropertiesTransformer.addTransformedInClassAtomic(AtomicfuJvmIrTransformer.kt:50)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.transformAtomicProperty(AbstractAtomicfuTransformer.kt:164)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitClass(AbstractAtomicfuTransformer.kt:139)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitClass(AbstractAtomicfuTransformer.kt:134)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
        at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:33)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transformChildren(IrFile.kt:38)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitFile(IrElementTransformer.kt:90)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitFile(AbstractAtomicfuTransformer.kt:151)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitFile(AbstractAtomicfuTransformer.kt:134)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:28)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:31)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer.transformAtomicProperties(AbstractAtomicfuTransformer.kt:111)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer.transform(AbstractAtomicfuTransformer.kt:97)
        at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuLoweringExtension.generate(AtomicfuLoweringExtension.kt:36)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.applyIrGenerationExtensions(convertToIr.kt:437)
        at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.runActualizationPipeline(convertToIr.kt:246)
        at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.convertToIrAndActualize(convertToIr.kt:130)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize(convertToIr.kt:99)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize$default(convertToIr.kt:72)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.convertToIrAndActualizeForJvm(jvmCompilerPipeline.kt:196)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.convertAnalyzedFirToIr(jvmCompilerPipeline.kt:169)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.compileModulesUsingFrontendIrAndLightTree(jvmCompilerPipeline.kt:140)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:148)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:43)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:103)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:464)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:73)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:506)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:423)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:301)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:129)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:675)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBa
```

**Comment by JavierSegoviaCordoba** [comment]
Is everything happening in the same module? Does it happen without `Redacted`?

**Comment by JavierSegoviaCordoba** [comment]
I have tried to reproduce it with no luck:

## Gradle dependencies

I have tried both `atomicfu` plugins, one with its version (0.25.0) and one with the Kotlin version (2.0.20).

```toml
[versions]
atomicfu = "0.25.0"
kopy = "0.6.1-devD.1+2.0.20"
kotlin = "2.0.20"
redacted = "1.10.0"

[plugins]
atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
kopy = { id = "com.javiersc.kotlin.kopy", version.ref = "kopy" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
redacted = { id = "dev.zacsweers.redacted", version.ref = "redacted" }
```

## Gradle config

```kotlin
plugins {
    application
    alias(libs.plugins.atomicfu)
    // alias(libs.plugins.kotlinx.atomicfu)
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kopy)
    alias(libs.plugins.redacted)
}

application {
    mainClass = "com.javiersc.kopy.playground.library.a.MainKt"
}

```

## Main code

```kotlin
import com.javiersc.kotlin.kopy.Kopy
import dev.zacsweers.redacted.annotations.Redacted

@Kopy data class Person(val name: Name, val address: Address, val privateInfo: PrivateInfo)

@Kopy data class Name(val first: String, val last: String)

@Kopy data class Address(val street: String, val city: String, val state: String, val zip: String)

data class PrivateInfo(@Redacted val ssn: String, @Redacted val dob: String)

fun main() {
    val address1 = Address(street = "Street", city = "City", state = "State", zip = "Zip")
    val name1 = Name(first = "First", last = "Last")
    val privateInfo1 = PrivateInfo(ssn = "SSN", dob = "DOB")
    val person1 = Person(name = name1, address = address1, privateInfo = privateInfo1)

    val person2 = person1.copy {
        privateInfo.ssn.set("SSN 42")
    }
    check(person2.privateInfo.ssn == "SSN 42") {
        "Fail: ${person2.privateInfo.ssn} is not equal to SSN 42"
    }
    println(person2)
}
```

Can you share a branch on your repo in which it is being reproduced?

**Comment by JavierSegoviaCordoba** [comment]
@sureshg I have seen a crash when using `kotlinx-atomicfu` in multimodule which is different from the crash you shared. Anyway the kotlinx plugin is using the Kotlin 2.0.0 version, can you try to use one which follows the Kotlin version?

```toml
[versions]
atomicfu = "0.25.0"
...

[plugins]
atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
...
```

**Comment by sureshg** [comment]
@JavierSegoviaCordoba all @Kopy code are in a shared module. IIUC, the kotlinx-atomic would apply the `plugin.atomicfu` with proper version kotlin version. I have IR transformations enabled for JVM and that's what causing this error (it's happening for both kotlinx and kotlin atomicfu plugins)

```
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlinx.atomicfu.enableJsIrTransformation=true
kotlinx.atomicfu.enableNativeIrTransformations=true
```

**Comment by sureshg** [comment]
By the way if we apply kotlin atomicfu compiler plugin, , how can we enable the `VarHandle` variant for jvm transformation? I think that option is available only for kotlinx plugin

```kotlin
atomicfu {
  transformJvm = true
  transformJs = true
  jvmVariant = "VH"
}
```

**Comment by sureshg** [comment]
Another issue is with nativeCompilation.

 * Enabled the new kotlin compiler plugin
 * Remove all IR transformation configuration
 * All i did is, added `alias(libs.plugins.kopy)` to shared module
 
 ```kotlin
 import com.javiersc.kotlin.kopy.Kopy
import dev.zacsweers.redacted.annotations.Redacted

@Kopy data class Person(val name: Name, val address: Address, val privateInfo: PrivateInfo)

@Kopy data class Name(val first: String, val last: String)

@Kopy data class Address(val street: String, val city: String, val state: String, val zip: String)

data class PrivateInfo(@Redacted val ssn: String, @Redacted val dob: String)
 ```

```
> Task :shared:compileKotlinLinuxArm64 FAILED
e: Compilation failed: While analysing /Users/sgopal1/code/kotlin-mpp-playground/shared/src/commonMain/kotlin/dev/suresh/lang/Person.kt:6:1: java.lang.NoClassDefFoundError: com/javiersc/kotlin/kopy/args/KopyFunctions

 * Source files: BuildConfig.kt, Greeting.kt, Platform.kt, Timer.kt, ByteArrayAsBase64Serializer.kt, Config.kt, HttpClient.kt, MediaApiClient.kt, Features.kt, HackersDelight.kt, Person.kt, Platform.kt, HttpClient.native.kt
 * Compiler version: 2.0.20
 * Output kind: LIBRARY

e: org.jetbrains.kotlin.util.FileAnalysisException: While analysing /Users/sgopal1/code/kotlin-mpp-playground/shared/src/commonMain/kotlin/dev/suresh/lang/Person.kt:6:1: java.lang.NoClassDefFoundError: com/javiersc/kotlin/kopy/args/KopyFunctions
        at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoFileAnalysisExceptionIfNeeded(AnalysisExceptions.kt:57)
        at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnFileAnalysis(Utils.kt:249)
        at org.jetbrains.kotlin.fir.resolve.transformers.AbstractFirStatusResolveTransformer.transformFile(FirStatusResolveTransformer.kt:542)
        at org.jetbrains.kotlin.fir.resolve.transformers.AbstractFirStatusResolveTransformer.transformFile(FirStatusResolveTransformer.kt:187)
        at org.jetbrains.kotlin.fir.declarations.FirFile.transform(FirFile.kt:46)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTransformerBasedResolveProcessor.processFile(FirResolveProcessor.kt:48)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTotalResolveProcessor.process(FirTotalResolveProcessor.kt:36)
        at org.jetbrains.kotlin.fir.pipeline.AnalyseKt.runResolution(analyse.kt:20)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.resolveAndCheckFir(firUtils.kt:76)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.buildResolveAndCheckFirViaLightTree(firUtils.kt:88)
        at org.jetbrains.kotlin.backend.konan.FirFrontendKt.firFrontendWithLightTree(FirFrontend.kt:128)
        at org.jetbrains.kotlin.backend.konan.driver.phases.FirFrontendKt.FIRPhase$lambda$1(FirFrontend.kt:28)
        at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$createSimpleNamedCompilerPhase$1.phaseBody(PhaseBuilders.kt:69)
        at org.jetbrains.kotlin.backend.common.phaser.SimpleNamedCompilerPhase.phaseBody(CompilerPhase.kt:226)
        at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:113)
        at org.jetbrains.kotlin.backend.konan.driver.PhaseEngine.runPhase(Machinery.kt:120)
        at org.jetbrains.kotlin.backend.konan.driver.PhaseEngine.runPhase$default(Machinery.kt:111)
        at org.jetbrains.kotlin.backend.konan.driver.phases.FirFrontendKt.runFirFrontend(FirFrontend.kt:35)
        at org.jetbrains.kotlin.backend.konan.driver.DynamicCompilerDriver.serializeKLibK2(DynamicCompilerDriver.kt:122)
```

**Comment by sureshg** [comment]
Sorry for putting everything in one issue. Let me know if you want to create separate issues

**Comment by JavierSegoviaCordoba** [comment]
@sureshg don't worry. I got the real issue about the multiplatform support and will fix it ASAP.

About the issue with `atomicfu`, I think the `atomicfu` compiler plugin is compiling the code before my compiler plugin changes the code in IR. I need to find a way to change the order (I know there is one, but I don't know how to do that right now).

Another option is generating the initializer of `_atomic` in FIR, which is not recommended but it would fix this ordering issue.

**Comment by JavierSegoviaCordoba** [comment]
About Kotlin Multiplatform, the next release should fix it, hopefully... 🥲 

About Atomicfu, the only solution until [this is addressed](https://youtrack.jetbrains.com/issue/KT-55300) is applying the Kopy plugin before the Atomicfu plugin.

**Comment by JavierSegoviaCordoba** [comment]
I hope that 0.10.0-2.0.20 fixes the multiplatform issue🤞. It will be published in a few minutes.

@sureshg as you are using convention plugins, to apply Kopy before Atomicfu, you need to move it into the convention plugin or apply the Atomicfu plugin per project, sorry!

**Comment by sureshg** [comment]
Thanks..i am trying to move the kopy to convention plugins using 
```kotlin
build-kopy-plugin                    = { module = "com.javiersc.kotlin:kopy-gradle-plugin"                          , version.ref = "kopy"}
```
But somehow gradle can't resolve this plugin and throws the following error
```
Could not resolve all artifacts for configuration 'classpath'.
> Could not find com.javiersc.kotlin:kopy-gradle-plugin:0.10.0+2.0.20.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.10.0+2.0.20/kopy-gradle-plugin-0.10.0+2.0.20.pom
  Required by:
      unspecified:unspecified:unspecified > project :build-logic

```

This is working for other thrid party plugins ..any idea whats wrong here?

**Comment by sureshg** [comment]
Getting a compilation error now.. it works fine on `0.9.0`

```
> Task :shared:compileKotlinJs FAILED
e: Plugin classpath entry points to a non-existent location: /app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-args/0.10.0+2.0.20/69f38aaa6128271da53b0314ee23c4df2d8c9c05/kopy-args-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-compiler-extensions/0.4.1+2.0.20/86cd31ce6287715868bfc17751c5eaa44e6a8b01/kotlin-compiler-extensions-0.4.1+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-runtime-jvm/0.10.0+2.0.20/77c2d17961d73664bea0b2c3eb05597b809fd6bd/kopy-runtime-jvm-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-stdlib-jvm/0.1.0-alpha.16/be7d925a5b3a84253a094c5f704fbe54674d9bcc/kotlin-stdlib-jvm-0.1.0-alpha.16.jar:/app/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-jvm/0.25.0/c8686b7f79a65516610b1ce4965bb450084075f2/atomicfu-jvm-0.25.0.jar

> Task :shared:compileCommonMainKotlinMetadata FAILED
e: Plugin classpath entry points to a non-existent location: /app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-args/0.10.0+2.0.20/69f38aaa6128271da53b0314ee23c4df2d8c9c05/kopy-args-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-compiler-extensions/0.4.1+2.0.20/86cd31ce6287715868bfc17751c5eaa44e6a8b01/kotlin-compiler-extensions-0.4.1+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-runtime-jvm/0.10.0+2.0.20/77c2d17961d73664bea0b2c3eb05597b809fd6bd/kopy-runtime-jvm-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-stdlib-jvm/0.1.0-alpha.16/be7d925a5b3a84253a094c5f704fbe54674d9bcc/kotlin-stdlib-jvm-0.1.0-alpha.16.jar:/app/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-jvm/0.25.0/c8686b7f79a65516610b1ce4965bb450084075f2/atomicfu-jvm-0.25.0.jar

```

**Comment by JavierSegoviaCordoba** [comment]
> Getting a compilation error now.. it works fine on `0.9.0`
> 
> 
> 
> ```
> 
> > Task :shared:compileKotlinJs FAILED
> 
> e: Plugin classpath entry points to a non-existent location: /app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-args/0.10.0+2.0.20/69f38aaa6128271da53b0314ee23c4df2d8c9c05/kopy-args-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-compiler-extensions/0.4.1+2.0.20/86cd31ce6287715868bfc17751c5eaa44e6a8b01/kotlin-compiler-extensions-0.4.1+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-runtime-jvm/0.10.0+2.0.20/77c2d17961d73664bea0b2c3eb05597b809fd6bd/kopy-runtime-jvm-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-stdlib-jvm/0.1.0-alpha.16/be7d925a5b3a84253a094c5f704fbe54674d9bcc/kotlin-stdlib-jvm-0.1.0-alpha.16.jar:/app/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-jvm/0.25.0/c8686b7f79a65516610b1ce4965bb450084075f2/atomicfu-jvm-0.25.0.jar
> 
> 
> 
> > Task :shared:compileCommonMainKotlinMetadata FAILED
> 
> e: Plugin classpath entry points to a non-existent location: /app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-args/0.10.0+2.0.20/69f38aaa6128271da53b0314ee23c4df2d8c9c05/kopy-args-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-compiler-extensions/0.4.1+2.0.20/86cd31ce6287715868bfc17751c5eaa44e6a8b01/kotlin-compiler-extensions-0.4.1+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kopy-runtime-jvm/0.10.0+2.0.20/77c2d17961d73664bea0b2c3eb05597b809fd6bd/kopy-runtime-jvm-0.10.0+2.0.20.jar:/app/.gradle/caches/modules-2/files-2.1/com.javiersc.kotlin/kotlin-stdlib-jvm/0.1.0-alpha.16/be7d925a5b3a84253a094c5f704fbe54674d9bcc/kotlin-stdlib-jvm-0.1.0-alpha.16.jar:/app/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/atomicfu-jvm/0.25.0/c8686b7f79a65516610b1ce4965bb450084075f2/atomicfu-jvm-0.25.0.jar
> 
> 
> 
> ```

Looks like the `asPath` function is using a different separator in macOS, I will fix this and add some tests.

About the problem in the convention plugin, I would have to investigate, it is a bit weird as it is here:

https://repo1.maven.org/maven2/com/javiersc/kotlin/kopy-gradle-plugin/0.10.0+2.0.20/

**Comment by JavierSegoviaCordoba** [comment]
@sureshg can you try the `0.10.1+2.0.20-SNAPSHOT`?

You need to add the repo `maven(url = "https://oss.sonatype.org/content/repositories/snapshots")` to your `repositories` blocks.

**Comment by sureshg** [comment]
@JavierSegoviaCordoba sorry for the delay. I am having a hard time using this snapshot library in build-logic convention plugins (because I have to apply Kopy before Atomicfu) ..whatever i do, I am getting the following error.

```kotlin
* What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not find com.javiersc.kotlin:kopy-gradle-plugin:0.10.1+2.0.20-SNAPSHOT.
  Searched in the following locations:
    - https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.10.1+2.0.20-SNAPSHOT/maven-metadata.xml
    - https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.10.1+2.0.20-SNAPSHOT/kopy-gradle-plugin-0.10.1+2.0.20-SNAPSHOT.pom
  Required by:
      unspecified:unspecified:unspecified > project :build-logic
```

Here is my build-logic settings.kts

```kotlin
pluginManagement {
  repositories {
    val mavenSnapshotRepo = providers.gradleProperty("mavenSnapshotRepo").orNull.toBoolean()
    val mavenSnapshotUrl = "https://oss.sonatype.org/content/repositories/snapshots"

    if (mavenSnapshotRepo) {
      maven(url = mavenSnapshotUrl) { mavenContent { snapshotsOnly() } }
    }
    mavenCentral()
    gradlePluginPortal()
  }
}

val mavenSnapshotRepo = providers.gradleProperty("mavenSnapshotRepo").orNull.toBoolean()
val mavenSnapshotUrl = "https://oss.sonatype.org/content/repositories/snapshots"

dependencyResolutionManagement {
  repositories {
    if (mavenSnapshotRepo) {
      maven(url = mavenSnapshotUrl) { mavenContent { snapshotsOnly() } }
    }
    mavenCentral()
    gradlePluginPortal()
  }
  versionCatalogs { register("libs") { from(files("../libs.versions.toml")) } }
  repositoriesMode = RepositoriesMode.FAIL_ON_PROJECT_REPOS
}
```

I have `mavenSnapshotRepo=true`

Is it possible to publish a version to central or gradle plugin repository?

**Comment by sureshg** [comment]
```kotlin
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Searched in the following locations:
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]     - https://plugins.gradle.org/m2/com/javiersc/kotlin/kopy-gradle-plugin/0.10.0+2.0.20/kopy-gradle-plugin-0.10.0+2.0.20.pom
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Required by:
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       unspecified:unspecified:unspecified > project :build-logic
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
2024-09-07T18:27:03.557-0700 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --stacktrace option to get the stack trace.
```

`If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.` - does this help ?

**Comment by sureshg** [comment]
Unfortunately, there is no way of using Kopy on the pre-compiled script plugin (with the current version) and using directly requires changes in the order of other compiler plugins. Moving atomicfu out of a conventional plugin and applying it to all other modules is tedious.

**Comment by JavierSegoviaCordoba** [comment]
@sureshg I am trying to reproduce it with `buildSrc`, and with `build-logic` as an included build, but in both use cases the build is successful with `./gradlew build` for me.

I have added a Gradle functional test as it runs on CI in all machines, including macOS ARM, but the test also passes.

Can you please share a branch that reproduces the issue?

![image](https://github.com/user-attachments/assets/854cfed8-f491-44d2-82ed-62776baa94f3)

**Comment by sureshg** [comment]
Could you share the Gradle plugin dependency added to the build-logic build.gradle.kts ?

**Comment by sureshg** [comment]
@JavierSegoviaCordoba could you try this one https://github.com/sureshg/kmp-issue/ ? It compiles until you add the plugin dependency in `build-logic` here - https://github.com/sureshg/kmp-issue/blob/main/gradle/build-logic/build.gradle.kts#L203

**Comment by sureshg** [comment]
@JavierSegoviaCordoba same error after adding the snapshot. By the way `kopy` plugin dependency was not added by default (https://github.com/sureshg/kmp-issue/blob/main/gradle/build-logic/build.gradle.kts#L203). I just enabled it. Could you pull the latest one and test on windows again? 

```
❯ ./gradlew assemble --refresh-dependencies
Configuration on demand is an incubating feature.
Type-safe project accessors is an incubating feature.

> Task :build-logic:jar
:jar: A valid plugin descriptor was found for com.gradle.develocity.properties but the implementation class com.gradle.develocity.agent.gradle.DevelocityPlugin was not found in the jar.

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all artifacts for configuration 'classpath'.
> Could not find com.javiersc.kotlin:kopy-gradle-plugin:0.10.1+2.0.20-SNAPSHOT.
  Required by:
      unspecified:unspecified:unspecified > project :build-logic

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

**Comment by sureshg** [comment]
The plugin loading issue is fixed by adding

```kotlin
pluginManagement {
  repositories {
    // https://github.com/gradle/gradle/issues/16654
    mavenCentral()
    gradlePluginPortal()
  }
  includeBuild("gradle/build-logic")
}
```

More details can be found in this issue - https://github.com/gradle/gradle/issues/16654
Really unintuitive behavior from Gradle.

**Comment by JavierSegoviaCordoba** [comment]
Nice 👍, agree with you about it is hard to diagnosis this one... In my repro which was working I copy pasted all repositories in the root one as I tend to do that in every side project I do 😆 

Is the compilation issue in KMP fixed too?

**Comment by sureshg** [comment]
Yes, I checked JVM, JS, WASM and Native targets..seems working fine. Thanks very much for fixing it. Now the only minor gripe is the plugin order. Hope that will also get fixed soon  :)

**Comment by JavierSegoviaCordoba** [comment]
Related: https://github.com/JavierSegoviaCordoba/kopy/issues/109#issuecomment-3485093614

It will not be necessary to apply the plugins in a specific order anymore.
